### ISSUE TITLE
Remover serviço

### ISSUE THREAD

**Issue by cv** [servicosgovbr/editor-de-servicos#189]
Há serviços que não existem mais, e gostariam de poder remover facilmente.

**Comment by sahrosa** [comment]
Se tivermos uma lista, podemos colocar a opção de deletar o serviço pela lista. 

Outra opção seria incluir a opção de excluir nesta barra do topo.

![image](https://cloud.githubusercontent.com/assets/2932644/8909340/392eff4e-3457-11e5-9996-cc4f505f330b.png)

O que acham?

**Comment by cv** [comment]
@kchnr tá tendo esse problema também?

```
00000000-0000-0000-0000-000000000000 ERROR [http-nio-8090-exec-5] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of push command] with root cause
java.io.IOException: Source ref passaporte doesn't resolve to any object.
	at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:288) ~[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at org.eclipse.jgit.transport.RemoteRefUpdate.<init>(RemoteRefUpdate.java:192) ~[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:646) ~[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at org.eclipse.jgit.transport.Transport.findRemoteRefUpdatesFor(Transport.java:1269) ~[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:153) ~[org.eclipse.jgit-4.0.1.201506240215-r.jar:4.0.1.201506240215-r]
	at br.gov.servicos.editor.servicos.Cartas.push(Cartas.java:226) ~[main/:na]
	at br.gov.servicos.editor.servicos.Cartas.lambda$excluir$9(Cartas.java:112) ~[main/:na]
	at br.gov.servicos.editor.servicos.Cartas$$Lambda$38/1661440216.apply(Unknown Source) ~[na:na]
	at br.gov.servicos.editor.servicos.Cartas.comRepositorioAberto(Cartas.java:292) ~[main/:na]
	at br.gov.servicos.editor.servicos.Cartas.excluir(Cartas.java:102) ~[main/:na]
	at br.gov.servicos.editor.servicos.ServicoController.excluirServico(ServicoController.java:66) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1]8.0_5
```
